package org.bh.platform.actionkeys;

public enum PlatformActionKey{
	
	/**
	 * ActionKeys of PlatformMenu
	 */
	FILENEW,
	FILEOPEN,
	FILECLOSE,
	FILESAVE,
	FILESAVEAS,
	FILEQUIT,
	PROJECTCREATE,
	PROJECTRENAME,
	PROJECTDUPLICATE,
	PROJECTIMPORT,
	PROJECTEXPORT,
	PROJECTREMOVE,
	SCENARIOCREATE,
	SCENARIORENAME,
	SCENARIODUPLICATE,
	SCENARIOMOVE,
	SCENARIOREMOVE,
	BILANZGUVSHOW,
	BILANZGUVCREATE,
	BILANZGUVIMPORT,
	BILANZGUVREMOVE,
	OPTIONSCHANGE,
	HELPUSERHELP,
	HELPMATHHELP,
	HELPINFO;
	
	/**
	 * ActionKeys of PlatformToolbar
	 */
	
	
	
	
}
